"""Removed medical conditions and allergies from child

Revision ID: 276b17de983a
Revises: 5e1c4b4dff47
Create Date: 2025-11-01 15:57:58.209411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276b17de983a'
down_revision: Union[str, Sequence[str], None] = '5e1c4b4dff47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'medical_conditions')
    op.drop_column('children', 'allergies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('allergies', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('children', sa.Column('medical_conditions', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
