"""vaccination models

Revision ID: 2d99f0451c69
Revises: e9826e377aa9
Create Date: 2025-11-14 00:25:48.898715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d99f0451c69'
down_revision: Union[str, Sequence[str], None] = 'e9826e377aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccination_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('protect_against', sa.String(), nullable=True),
    sa.Column('doses_needed', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vaccine_name')
    )
    op.create_table('vaccination_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vaccine_id', sa.UUID(), nullable=False),
    sa.Column('dose_num', sa.Integer(), nullable=False),
    sa.Column('min_age_days', sa.Integer(), nullable=False),
    sa.Column('max_age_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccination_options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccination_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('dose_num', sa.Integer(), nullable=False),
    sa.Column('date_given', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GIVEN', 'MISSED', name='vaccination_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['vaccination_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccination_options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feeding_preferences')
    op.drop_table('vaccinations')
    op.drop_table('milestones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('milestones_child_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('milestones_pkey'))
    )
    op.create_table('vaccinations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vaccine_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_given', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('vaccinations_child_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vaccinations_pkey'))
    )
    op.create_table('feeding_preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feeding_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('feeding_preferences_child_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feeding_preferences_pkey'))
    )
    op.drop_table('vaccination_records')
    op.drop_table('vaccination_schedules')
    op.drop_table('vaccination_options')
    # ### end Alembic commands ###
