"""Added complete field to migrations

Revision ID: 629447e6d99a
Revises: f679823ec526
Create Date: 2025-11-03 00:20:14.121367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629447e6d99a'
down_revision: Union[str, Sequence[str], None] = 'f679823ec526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccinations', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccinations', 'completed')
    # ### end Alembic commands ###
