"""add created_at, updated_at to medical condition

Revision ID: 69b7a4ecc1f3
Revises: 9829f9e0de8a
Create Date: 2025-11-02 12:58:16.219533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b7a4ecc1f3'
down_revision: Union[str, Sequence[str], None] = '9829f9e0de8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_conditions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('medical_conditions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_conditions', 'updated_at')
    op.drop_column('medical_conditions', 'created_at')
    # ### end Alembic commands ###
