"""Added complete field to migrations

Revision ID: 6a0539f1b3e5
Revises: 629447e6d99a
Create Date: 2025-11-03 00:26:15.751235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0539f1b3e5'
down_revision: Union[str, Sequence[str], None] = '629447e6d99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccinations', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccinations', 'due_date')
    # ### end Alembic commands ###
