"""updated models

Revision ID: 9829f9e0de8a
Revises: 2d0176625f68
Create Date: 2025-11-02 12:35:37.932069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9829f9e0de8a'
down_revision: Union[str, Sequence[str], None] = '2d0176625f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('allergen', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('diagnosed_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergies_child_id'), 'allergies', ['child_id'], unique=False)
    op.create_table('medical_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('condition_name', sa.String(), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=True),
    sa.Column('treatment', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_conditions_child_id'), 'medical_conditions', ['child_id'], unique=False)
    op.alter_column('children', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index(op.f('ix_children_mother_id'), 'children', ['mother_id'], unique=False)
    op.drop_constraint(op.f('children_mother_id_fkey'), 'children', type_='foreignkey')
    op.create_foreign_key(None, 'children', 'users', ['mother_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_feeding_preferences_child_id'), 'feeding_preferences', ['child_id'], unique=False)
    op.drop_constraint(op.f('feeding_preferences_child_id_fkey'), 'feeding_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'feeding_preferences', 'children', ['child_id'], ['id'], ondelete='CASCADE')
    op.alter_column('milestones', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_constraint(op.f('milestones_child_id_fkey'), 'milestones', type_='foreignkey')
    op.create_foreign_key(None, 'milestones', 'children', ['child_id'], ['id'], ondelete='CASCADE')
    op.add_column('vaccinations', sa.Column('dose', sa.String(), nullable=True))
    op.add_column('vaccinations', sa.Column('notes', sa.String(), nullable=True))
    op.create_index(op.f('ix_vaccinations_child_id'), 'vaccinations', ['child_id'], unique=False)
    op.drop_constraint(op.f('vaccinations_child_id_fkey'), 'vaccinations', type_='foreignkey')
    op.create_foreign_key(None, 'vaccinations', 'children', ['child_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaccinations', type_='foreignkey')
    op.create_foreign_key(op.f('vaccinations_child_id_fkey'), 'vaccinations', 'children', ['child_id'], ['id'])
    op.drop_index(op.f('ix_vaccinations_child_id'), table_name='vaccinations')
    op.drop_column('vaccinations', 'notes')
    op.drop_column('vaccinations', 'dose')
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.create_foreign_key(op.f('milestones_child_id_fkey'), 'milestones', 'children', ['child_id'], ['id'])
    op.alter_column('milestones', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'feeding_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('feeding_preferences_child_id_fkey'), 'feeding_preferences', 'children', ['child_id'], ['id'])
    op.drop_index(op.f('ix_feeding_preferences_child_id'), table_name='feeding_preferences')
    op.drop_constraint(None, 'children', type_='foreignkey')
    op.create_foreign_key(op.f('children_mother_id_fkey'), 'children', 'users', ['mother_id'], ['id'])
    op.drop_index(op.f('ix_children_mother_id'), table_name='children')
    op.alter_column('children', 'date_of_birth',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_medical_conditions_child_id'), table_name='medical_conditions')
    op.drop_table('medical_conditions')
    op.drop_index(op.f('ix_allergies_child_id'), table_name='allergies')
    op.drop_table('allergies')
    # ### end Alembic commands ###
