"""add chatbot messages

Revision ID: 9d321af77ee0
Revises: b1e6db2202f0
Create Date: 2025-11-25 07:44:56.338692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d321af77ee0'
down_revision: Union[str, Sequence[str], None] = 'b1e6db2202f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.Enum('HUMAN', 'AI', 'SYSTEM', name='messagetype'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['aibots.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_messages_chatbot_id'), 'chatbot_messages', ['chatbot_id'], unique=False)
    op.create_index(op.f('ix_chatbot_messages_conversation_id'), 'chatbot_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chatbot_messages_user_id'), 'chatbot_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbot_messages_user_id'), table_name='chatbot_messages')
    op.drop_index(op.f('ix_chatbot_messages_conversation_id'), table_name='chatbot_messages')
    op.drop_index(op.f('ix_chatbot_messages_chatbot_id'), table_name='chatbot_messages')
    op.drop_table('chatbot_messages')
    # ### end Alembic commands ###
