"""removed fields

Revision ID: b10f9e6b14db
Revises: b2bfa26ef895
Create Date: 2025-12-08 19:21:15.644218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b10f9e6b14db'
down_revision: Union[str, Sequence[str], None] = 'b2bfa26ef895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccination_records', 'dose_num')
    op.drop_column('vaccination_records', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccination_records', sa.Column('status', postgresql.ENUM('PENDING', 'GIVEN', 'MISSED', 'Given', name='vaccination_status_enum'), autoincrement=False, nullable=False))
    op.add_column('vaccination_records', sa.Column('dose_num', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
