"""add vaccine reminders

Revision ID: b1e6db2202f0
Revises: 1f8928b6c216
Create Date: 2025-11-24 20:43:42.420353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e6db2202f0'
down_revision: Union[str, Sequence[str], None] = '1f8928b6c216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccination_reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_id', sa.UUID(), nullable=False),
    sa.Column('reminder', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccination_options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccination_reminders')
    # ### end Alembic commands ###
