"""add child growth records

Revision ID: b6b5819e306c
Revises: c58710dcdf83
Create Date: 2026-01-07 17:47:00.682940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6b5819e306c'
down_revision: Union[str, Sequence[str], None] = 'c58710dcdf83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_growth_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('head_circumference', sa.Float(), nullable=True),
    sa.Column('milestone_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'recorded_at', name='uq_child_growth_child_date')
    )
    op.create_index('ix_child_growth_child_date', 'child_growth_records', ['child_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_child_growth_records_child_id'), 'child_growth_records', ['child_id'], unique=False)
    op.create_index(op.f('ix_child_growth_records_recorded_at'), 'child_growth_records', ['recorded_at'], unique=False)
    op.drop_table('notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notification_type', postgresql.ENUM('VACCINATION', 'GROWTH', 'MILESTONE', 'SETTINGS', 'COMMENT', 'MENTION', 'LIKE', name='notification_type_enum'), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('receiver', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiver'], ['users.id'], name=op.f('notifications_receiver_fkey')),
    sa.ForeignKeyConstraint(['sender'], ['users.id'], name=op.f('notifications_sender_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.drop_index(op.f('ix_child_growth_records_recorded_at'), table_name='child_growth_records')
    op.drop_index(op.f('ix_child_growth_records_child_id'), table_name='child_growth_records')
    op.drop_index('ix_child_growth_child_date', table_name='child_growth_records')
    op.drop_table('child_growth_records')
    # ### end Alembic commands ###
