"""Advanced user profile

Revision ID: d60f33a80090
Revises: 8359dfda45f8
Create Date: 2025-10-31 23:53:35.029901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60f33a80090'
down_revision: Union[str, Sequence[str], None] = '8359dfda45f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('number_of_children', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('blood_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notification_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('account_created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_created_at')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'notification_enabled')
    op.drop_column('users', 'blood_type')
    op.drop_column('users', 'number_of_children')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
