"""added index to post created at

Revision ID: e99014e7ad04
Revises: b10f9e6b14db
Create Date: 2025-12-09 00:28:05.392418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99014e7ad04'
down_revision: Union[str, Sequence[str], None] = 'b10f9e6b14db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    # ### end Alembic commands ###
