"""add created_at, updated_at

Revision ID: f679823ec526
Revises: 69b7a4ecc1f3
Create Date: 2025-11-02 13:19:52.968591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f679823ec526'
down_revision: Union[str, Sequence[str], None] = '69b7a4ecc1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('allergies', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('feeding_preferences', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('feeding_preferences', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('milestones', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('milestones', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('vaccinations', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('vaccinations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccinations', 'updated_at')
    op.drop_column('vaccinations', 'created_at')
    op.drop_column('milestones', 'updated_at')
    op.drop_column('milestones', 'created_at')
    op.drop_column('feeding_preferences', 'updated_at')
    op.drop_column('feeding_preferences', 'created_at')
    op.drop_column('allergies', 'updated_at')
    op.drop_column('allergies', 'created_at')
    # ### end Alembic commands ###
