"""update ai message

Revision ID: 317f1b621f64
Revises: 982a3101d50a
Create Date: 2026-01-23 21:19:21.791550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317f1b621f64'
down_revision: Union[str, Sequence[str], None] = '982a3101d50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot_messages', 'chatbot_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot_messages', 'chatbot_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
