"""update AI Conversation

Revision ID: 982a3101d50a
Revises: d9b842a30086
Create Date: 2026-01-23 16:40:18.609816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982a3101d50a'
down_revision: Union[str, Sequence[str], None] = 'd9b842a30086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_conversations', sa.Column('messages_exist', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_conversations', 'messages_exist')
    # ### end Alembic commands ###
