"""update AIConversation

Revision ID: 9decfb3d81e9
Revises: 1974ef5f33c0
Create Date: 2026-01-12 17:47:17.891389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9decfb3d81e9'
down_revision: Union[str, Sequence[str], None] = '1974ef5f33c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_conversations', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('ai_conversations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('chatbot_messages', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot_messages', 'updated_at')
    op.drop_column('ai_conversations', 'updated_at')
    op.drop_column('ai_conversations', 'created_at')
    # ### end Alembic commands ###
