"""update: conversation, message

Revision ID: a1ae751b7677
Revises: c17cfd4b4e08
Create Date: 2026-03-16 21:29:09.763666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ae751b7677'
down_revision: Union[str, Sequence[str], None] = 'c17cfd4b4e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.Enum('HUMAN', 'AI', name='messagetype'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_messages_conversation_id'), 'chatbot_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chatbot_messages_user_id'), 'chatbot_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbot_messages_user_id'), table_name='chatbot_messages')
    op.drop_index(op.f('ix_chatbot_messages_conversation_id'), table_name='chatbot_messages')
    op.drop_table('chatbot_messages')
    # ### end Alembic commands ###
