"""update user

Revision ID: ddb2616c3727
Revises: 990711e5b6d1
Create Date: 2026-02-21 03:24:22.114828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'ddb2616c3727'
down_revision: Union[str, Sequence[str], None] = '990711e5b6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type FIRST
    userrole_enum = ENUM('ADMIN', 'USER', name='userrole', create_type=True)
    userrole_enum.create(op.get_bind(), checkfirst=True)
    
    # Then add the column using the enum type
    op.add_column('users', sa.Column('role', sa.Enum(name='userrole'), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the column FIRST
    op.drop_column('users', 'role')
    
    # Then drop the enum type
    userrole_enum = ENUM('ADMIN', 'USER', name='userrole', create_type=True)
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###