"""generate notifications)

Revision ID: fa9e159b98cb
Revises: 3df6529dd229
Create Date: 2026-01-07 19:46:03.195021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa9e159b98cb'
down_revision: Union[str, Sequence[str], None] = '3df6529dd229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('VACCINATION', 'GROWTH', 'MILESTONE', 'SETTINGS', 'COMMENT', 'MENTION', 'LIKE', name='notification_type_enum'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('receiver', sa.UUID(), nullable=False),
    sa.Column('sender', sa.UUID(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['receiver'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
